-- MySQL Script generated by MySQL Workbench
-- 01/27/19 11:02:48
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tasklib
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `tasklib` ;

-- -----------------------------------------------------
-- Schema tasklib
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tasklib` DEFAULT CHARACTER SET utf8 ;
USE `tasklib` ;

-- -----------------------------------------------------
-- Table `tasklib`.`student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tasklib`.`student` ;

CREATE TABLE IF NOT EXISTS `tasklib`.`student` (
  `id` BIGINT(20) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `email_confirmed` ENUM('0', '1') NULL,
  `register` VARCHAR(25) NULL,
  `status` ENUM('active', 'inactive') NOT NULL DEFAULT 'inactive',
  `created_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tasklib`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tasklib`.`category` ;

CREATE TABLE IF NOT EXISTS `tasklib`.`category` (
  `id` BIGINT(20) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `created_date` DATETIME NOT NULL,
  `task_type` SET('Mathematic', 'Physics', 'Chemistry') NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tasklib`.`level`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tasklib`.`level` ;

CREATE TABLE IF NOT EXISTS `tasklib`.`level` (
  `id` BIGINT(20) NOT NULL,
  `level_name` VARCHAR(255) NULL,
  `created_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `category_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_level_category_id` (`category_id` ASC),
  CONSTRAINT `fk_level_category_id`
    FOREIGN KEY (`category_id`)
    REFERENCES `tasklib`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tasklib`.`variant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tasklib`.`variant` ;

CREATE TABLE IF NOT EXISTS `tasklib`.`variant` (
  `id` BIGINT(20) NOT NULL,
  `name` VARCHAR(45) CHARACTER SET 'utf8' NULL,
  `created_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tasklib`.`task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tasklib`.`task` ;

CREATE TABLE IF NOT EXISTS `tasklib`.`task` (
  `id` BIGINT(20) NOT NULL,
  `task` LONGTEXT NULL,
  `description` LONGTEXT NULL,
  `created_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `type` ENUM('Mathematic', 'Physics', 'Chemistry') NOT NULL,
  `category_id` BIGINT(20) DEFAULT NULL,
  `level_id` BIGINT(20) NOT NULL,
  `variant_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_task_category1_idx` (`category_id` ASC),
  INDEX `fk_task_level1_idx` (`level_id` ASC),
  INDEX `fk_task_variant1_idx` (`variant_id` ASC),
  CONSTRAINT `fk_task_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `tasklib`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_task_level1`
    FOREIGN KEY (`level_id`)
    REFERENCES `tasklib`.`level` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_task_variant1`
    FOREIGN KEY (`variant_id`)
    REFERENCES `tasklib`.`variant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tasklib`.`response`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tasklib`.`response` ;

CREATE TABLE IF NOT EXISTS `tasklib`.`response` (
  `id` BIGINT(20) NOT NULL,
  `response` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `status` ENUM('0', '1') NULL,
  `task_id` BIGINT(20) NOT NULL,
  `created_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_answer_task1_idx` (`task_id` ASC),
  CONSTRAINT `fk_answer_task1`
    FOREIGN KEY (`task_id`)
    REFERENCES `tasklib`.`task` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tasklib`.`rt_service`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tasklib`.`rt_service` ;

CREATE TABLE IF NOT EXISTS `tasklib`.`rt_service` (
  `id` BIGINT(20) NOT NULL,
  `created_date` DATETIME NOT NULL,
  `student_id` BIGINT(20) NOT NULL,
  `variant_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_rt_service_variant1_idx` (`variant_id` ASC),
  INDEX `fk_rt_service_student1_idx` (`student_id` ASC),
  CONSTRAINT `fk_rt_service_variant1`
    FOREIGN KEY (`variant_id`)
    REFERENCES `tasklib`.`variant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rt_service_student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `tasklib`.`student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tasklib`.`summary`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tasklib`.`summary` ;

CREATE TABLE IF NOT EXISTS `tasklib`.`summary` (
  `id` BIGINT(20) NOT NULL,
  `response_id` INT NOT NULL,
  `student_id` INT NOT NULL,
  `task_id` INT NOT NULL,
  `created_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_summary_student1_idx` (`student_id` ASC),
  INDEX `fk_summary_response1_idx` (`response_id` ASC),
  INDEX `fk_summary_task1_idx` (`task_id` ASC),
  CONSTRAINT `fk_summary_student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `tasklib`.`student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_summary_response1`
    FOREIGN KEY (`response_id`)
    REFERENCES `tasklib`.`response` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_summary_task1`
    FOREIGN KEY (`task_id`)
    REFERENCES `tasklib`.`task` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tasklib`.`task_images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tasklib`.`task_images` ;

CREATE TABLE IF NOT EXISTS `tasklib`.`task_images` (
  `id` INT NOT NULL,
  `image_name` LONGTEXT NULL,
  `created_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `task_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_task_images_task1_idx` (`task_id` ASC),
  CONSTRAINT `fk_task_images_task1`
    FOREIGN KEY (`task_id`)
    REFERENCES `tasklib`.`task` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
